apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-30T10:44:32Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "10506"
  uid: 3c3eff4b-f459-488d-8b15-368e8d073906
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.100.213.19
  clusterIPs:
  - 10.100.213.19
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30510
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
